version: "3.8"
services:
  db:
    image: postgres:14.1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=Budgy
      - POSTGRES_PASSWORD=Budgy
      - POSTGRES_DB=budgy_development

  web:
    build: .
    # image: surajwaghmare35/budget-app-web
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
            rails db:create db:migrate &&
            bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    depends_on:
      - db
    env_file:
      - .env # Specify the path to your .env file

volumes:
  pgdata:
