apiVersion: v1
kind: Secret
metadata:
  # name: regcred
  name: docker-credentials
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMzVnlZV3AzWVdkb2JXRnlaVE0xT21SamEzSmZjR0YwWDBRemJIVklURk5vTWxkVFdHMUVZbXRsZWprd1YwRm5OWGMyUlE9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
