apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: default
  hostPath:
    path: /tmp/pgdata
    # hard-coded local path
    type: DirectoryOrCreate
