apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-app-argocd
spec:
  destination:
    name: ""
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: manifests
    repoURL: "https://github.com/Surajwaghmare35/Budget-App-Rb"
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
